In [116]:
import torch
import numpy as np

In [5]:
a = torch.randn(10,1)

In [17]:
b=((a.repeat(3,1,1)-0.1)**2)
print(b)

tensor([[[1.6815e-03],
         [1.5734e-01],
         [1.1424e+00],
         [2.4835e+00],
         [3.3585e-01],
         [3.3889e+00],
         [6.8936e-01],
         [1.5005e-03],
         [2.3799e+00],
         [2.1039e-01]],

        [[1.6815e-03],
         [1.5734e-01],
         [1.1424e+00],
         [2.4835e+00],
         [3.3585e-01],
         [3.3889e+00],
         [6.8936e-01],
         [1.5005e-03],
         [2.3799e+00],
         [2.1039e-01]],

        [[1.6815e-03],
         [1.5734e-01],
         [1.1424e+00],
         [2.4835e+00],
         [3.3585e-01],
         [3.3889e+00],
         [6.8936e-01],
         [1.5005e-03],
         [2.3799e+00],
         [2.1039e-01]]])


In [22]:
print(b.shape)
print(b.sum().shape)
print(b.sum(1).shape)
print(b.sum(2).shape)

torch.Size([3, 10, 1])
torch.Size([])
torch.Size([3, 1])
torch.Size([3, 10])


In [28]:
sigma = torch.randn(1).repeat(10,1)
print(1/sigma)

tensor([[1.5270],
        [1.5270],
        [1.5270],
        [1.5270],
        [1.5270],
        [1.5270],
        [1.5270],
        [1.5270],
        [1.5270],
        [1.5270]])


In [29]:
(b/sigma).shape

torch.Size([3, 10, 1])

In [30]:
(b/sigma)

tensor([[[2.5677e-03],
         [2.4026e-01],
         [1.7445e+00],
         [3.7923e+00],
         [5.1285e-01],
         [5.1749e+00],
         [1.0527e+00],
         [2.2912e-03],
         [3.6342e+00],
         [3.2126e-01]],

        [[2.5677e-03],
         [2.4026e-01],
         [1.7445e+00],
         [3.7923e+00],
         [5.1285e-01],
         [5.1749e+00],
         [1.0527e+00],
         [2.2912e-03],
         [3.6342e+00],
         [3.2126e-01]],

        [[2.5677e-03],
         [2.4026e-01],
         [1.7445e+00],
         [3.7923e+00],
         [5.1285e-01],
         [5.1749e+00],
         [1.0527e+00],
         [2.2912e-03],
         [3.6342e+00],
         [3.2126e-01]]])

In [48]:
q_f_sig = torch.stack([torch.eye(10) for m in range(3)])
print(q_f_sig)

tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],

        [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0.,

In [49]:
torch.stack([torch.diag(q_f_sig[m]) for m in range(3)])

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
torch.diag(q_f_sig[1]).shape

torch.Size([10])

In [51]:
torch.diag(q_f_sig[1]/sigma)

tensor([1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270,
        1.5270])

In [61]:
d =torch.stack([torch.diag(q_f_sig[m]/sigma) for m in range(3)])
print(d)
print(d.shape)

tensor([[1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270,
         1.5270],
        [1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270,
         1.5270],
        [1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270, 1.5270,
         1.5270]])
torch.Size([3, 10])


In [59]:
e = torch.randn(3,10)

In [73]:
f = -0.5*torch.log(sigma).repeat(3,1,1).sum(2)

In [74]:
f.shape

torch.Size([3, 10])

In [136]:
q_z_pi = torch.randn(3, 10) / 3

In [137]:
q_z_pi.shape

torch.Size([3, 10])

In [139]:
q_z_pi[q_z_pi<0]=0

In [140]:
q_z_pi

tensor([[0.3568, 0.0000, 0.0000, 0.1667, 0.0000, 0.0000, 0.0000, 0.0572, 0.2250,
         0.1970],
        [0.1140, 0.4913, 0.9002, 0.0000, 0.0000, 0.0000, 0.2887, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.2669, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [152]:
(q_z_pi[0][...,None]/sigma).sum(1).shape

torch.Size([10])

In [153]:
(q_z_pi[0][...,None]/sigma).shape

torch.Size([10, 1])

In [165]:
Psi = sigma.sum(1).repeat(3,1)

In [167]:
Psi[1]

tensor([0.6549, 0.6549, 0.6549, 0.6549, 0.6549, 0.6549, 0.6549, 0.6549, 0.6549,
        0.6549])

In [168]:
0.5*(q_z_pi[1]*torch.log(np.pi*2*Psi[1])).sum()

tensor(1.2690)

In [126]:
psi = 0.01

In [127]:
q_z_pi

tensor([[0.2766, 0.0920, 0.0000, 0.2978, 0.4485, 0.2349, 0.4956, 0.1278, 0.3277,
         0.1625],
        [0.0000, 0.3681, 0.0000, 0.0125, 0.0000, 0.1935, 0.0000, 0.0000, 0.3446,
         0.0000],
        [0.2628, 0.0000, 0.0000, 0.0000, 0.0325, 0.8946, 0.0984, 0.0000, 0.0000,
         0.0000]])

In [134]:
q_z_pi/= psi

In [183]:
Y = torch.ones(10,2)*2
q_f_mean = torch.ones(2,10,2)
psi = torch.ones(10,2)*3
print((((Y.repeat(2,1,1)-q_f_mean)**2)/psi).shape)
print((((Y.repeat(2,1,1)-q_f_mean)**2)/psi))

torch.Size([2, 10, 2])
tensor([[[0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333]],

        [[0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333],
         [0.3333, 0.3333]]])


In [184]:
Y*psi

tensor([[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]])