In [23]:
import torch
import numpy as np

In [13]:
a = torch.randn(3)

In [14]:
a.diag(0)

tensor([[ 2.3506,  0.0000,  0.0000],
        [ 0.0000,  0.5953,  0.0000],
        [ 0.0000,  0.0000, -0.1986]])

In [19]:
b= torch.randn(1).repeat(3)

In [20]:
b.diag(0)

tensor([[0.2672, 0.0000, 0.0000],
        [0.0000, 0.2672, 0.0000],
        [0.0000, 0.0000, 0.2672]])

In [26]:
c = torch.tensor(np.log(0.05)).float().repeat(3)

In [31]:
d= c.diag(0)

In [33]:
torch.exp(c).diag()

tensor([[0.0500, 0.0000, 0.0000],
        [0.0000, 0.0500, 0.0000],
        [0.0000, 0.0000, 0.0500]])